# Generated by Django 6.1 on 2026-09-08 01:53

from django.db import migrations, models
from django.db.models import Q


def create_admin_role(apps, schema_editor):
    """specs/permissions.md: seeds the built-in ADMIN role and grants it to
    everyone who already had Manager access under the old is_staff/
    is_superuser gate, so nobody loses access when this ships.
    """
    Role = apps.get_model('accounts', 'Role')
    User = apps.get_model('accounts', 'User')

    role, _ = Role.objects.get_or_create(
        name='ADMIN', defaults={'description': 'Full Manager access. Equivalent to Superuser.'}
    )
    if not role.is_admin:
        role.is_admin = True
        role.save(update_fields=['is_admin'])

    for user in User.objects.filter(Q(is_staff=True) | Q(is_superuser=True)):
        user.roles.add(role)
        if not user.is_superuser:
            user.is_superuser = True
            user.save(update_fields=['is_superuser'])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(create_admin_role, noop),
    ]
