# Generated by Django 6.1 on 2026-08-08 21:53

import portal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NavTree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.JSONField(default=portal.models.default_nav_tree)),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.CharField(default='*', max_length=30)),
                ('key', models.CharField(max_length=120)),
                ('value', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'ordering': ['profile', 'key'],
                'unique_together': {('profile', 'key')},
            },
        ),
    ]
