# Generated by Django 6.1 on 2026-08-08 21:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('connections', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.SlugField(max_length=30, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('path', models.CharField(blank=True, max_length=500)),
                ('url', models.CharField(blank=True, max_length=500)),
                ('request_type', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST')], default='GET', max_length=4)),
                ('request_body', models.TextField(blank=True)),
                ('default_params', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(blank=True, limit_choices_to={'type': 'rest'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='connections.dataconnection')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SqlDef',
            fields=[
                ('id', models.SlugField(max_length=30, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('content', models.TextField(help_text='SQL text using :param bind variables')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
