# Generated by Django 6.1 on 2026-08-16 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='headers',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
