# Generated by Django 6.1 on 2026-09-13 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_action_headers'),
        ('datastore', '0010_remove_datastore_action_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Action',
        ),
    ]
