# Generated by Django 6.1 on 2026-08-08 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('connections', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datastore',
            fields=[
                ('id', models.SlugField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('source_type', models.CharField(choices=[('query', 'SQL query'), ('action', 'Action (REST)')], max_length=10)),
                ('inline_sql', models.TextField(blank=True, help_text='Used when sql_def is not set')),
                ('row_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('default_params', models.JSONField(blank=True, default=dict)),
                ('refresh_mode', models.CharField(choices=[('on_demand', 'On demand'), ('scheduled', 'Scheduled (cron)')], default='on_demand', max_length=10)),
                ('cron_schedule', models.CharField(blank=True, help_text='Cron expression (min hour day month day_of_week), used when refresh_mode=scheduled', max_length=60)),
                ('last_result', models.JSONField(blank=True, null=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.action')),
                ('connection', models.ForeignKey(blank=True, limit_choices_to={'type': 'sql'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='connections.dataconnection')),
                ('sql_def', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.sqldef')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
