# Generated by Django 6.1 on 2026-08-16 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0003_sample_connections'),
        ('datastore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datastore',
            name='file_expression',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='datastore',
            name='object_key',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='datastore',
            name='renderer_config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='datastore',
            name='renderer_type',
            field=models.CharField(blank=True, choices=[('none', 'None (raw JSON response)'), ('json', 'JSON (JsonPath columns)'), ('xml', 'XML (XPath columns)'), ('delimited', 'Delimited text'), ('fixed_width', 'Fixed width')], default='none', max_length=15),
        ),
        migrations.AlterField(
            model_name='datastore',
            name='connection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='connections.dataconnection'),
        ),
        migrations.AlterField(
            model_name='datastore',
            name='source_type',
            field=models.CharField(choices=[('query', 'SQL query'), ('action', 'Action (REST)'), ('s3', 'S3 object'), ('file', 'File')], max_length=10),
        ),
    ]
