# Generated by Django 6.1 on 2026-08-30 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datastore', '0002_datastore_file_expression_datastore_object_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datastore',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='datastore',
            name='data_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='datastore',
            name='json_root_path',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='datastore',
            name='source_type',
            field=models.CharField(choices=[('query', 'SQL query'), ('action', 'Action (REST)'), ('s3', 'S3 object'), ('file', 'File'), ('json', 'JSON')], max_length=10),
        ),
    ]
