# Generated by Django 6.1 on 2026-09-06 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('datastore', '0003_datastore_body_datastore_data_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datastore',
            name='allowed_roles',
            field=models.ManyToManyField(blank=True, related_name='datastores', to='accounts.role'),
        ),
    ]
