# Generated by Django 6.1 on 2026-09-07 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datastore', '0004_datastore_allowed_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='datastore',
            name='idle_timeout_seconds',
            field=models.PositiveIntegerField(blank=True, default=60, help_text='Stop refreshing after this many seconds with no connected viewers (blank/0 = never stop). Scheduled refresh only.', null=True),
        ),
    ]
