# Generated by Django 6.1 on 2026-09-08 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datastore', '0005_datastore_idle_timeout_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='datastore',
            name='api_mode',
            field=models.CharField(blank=True, choices=[('none', 'Disabled'), ('pull', 'Pull'), ('push', 'Push')], default='none', max_length=10),
        ),
    ]
