# Generated by Django 6.1 on 2026-09-13 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datastore', '0006_datastore_api_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datastore',
            name='file_expression',
        ),
        migrations.AlterField(
            model_name='datastore',
            name='source_type',
            field=models.CharField(choices=[('query', 'SQL query'), ('action', 'Action (REST)'), ('s3', 'S3 object'), ('json', 'JSON')], max_length=10),
        ),
    ]
