# Generated by Django 6.1 on 2026-09-13 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datastore', '0007_remove_datastore_file_expression_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datastore',
            name='access_type',
            field=models.CharField(blank=True, choices=[('http', 'HTTP request'), ('s3', 'S3 bucket'), ('file', 'File')], max_length=6),
        ),
        migrations.AddField(
            model_name='datastore',
            name='file_expression',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='datastore',
            name='file_path',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='datastore',
            name='object_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='datastore',
            name='request_body',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='datastore',
            name='request_method',
            field=models.CharField(blank=True, choices=[('GET', 'GET'), ('POST', 'POST')], default='GET', max_length=6),
        ),
        migrations.AddField(
            model_name='datastore',
            name='request_params',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='datastore',
            name='source_type',
            field=models.CharField(choices=[('query', 'SQL query'), ('action', 'Action (REST)'), ('s3', 'S3 object'), ('json', 'JSON'), ('serialized', 'Serialized Data')], max_length=10),
        ),
    ]
