# Generated by Django 6.1 on 2026-09-13 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datastore', '0008_datastore_access_type_datastore_file_expression_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datastore',
            name='name',
        ),
    ]
