# Generated by Django 6.1 on 2026-09-13 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datastore', '0009_remove_datastore_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datastore',
            name='action',
        ),
        migrations.RemoveField(
            model_name='datastore',
            name='json_root_path',
        ),
        migrations.AlterField(
            model_name='datastore',
            name='source_type',
            field=models.CharField(choices=[('query', 'SQL query'), ('serialized', 'Serialized Data')], max_length=10),
        ),
    ]
