# Generated by Django 6.1 on 2026-09-21 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datastore', '0010_remove_datastore_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datastore',
            name='cache_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
