# Generated by Django 6.1 on 2026-10-01 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datastore', '0011_datastore_cache_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='datastore',
            name='set_parameter_field',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='datastore',
            name='set_parameter_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
