# Generated by Django 6.1 on 2026-10-04 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datastore', '0011_datastore_cache_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='datastore',
            name='source_datastore',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='datastore',
            name='access_type',
            field=models.CharField(blank=True, choices=[('http', 'HTTP request'), ('s3', 'S3 bucket'), ('file', 'File'), ('datastore', 'Datastore'), ('embedded', 'Embedded Data')], max_length=9),
        ),
        migrations.AlterField(
            model_name='datastore',
            name='renderer_type',
            field=models.CharField(blank=True, choices=[('none', 'No Processing'), ('json', 'JSON (JsonPath columns)'), ('xml', 'XML (XPath columns)'), ('delimited', 'Delimited text'), ('fixed_width', 'Fixed width')], default='none', max_length=15),
        ),
    ]
