# Generated by Django 6.1 on 2026-10-01 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datastore', '0012_datastore_set_parameter_field_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datastore',
            name='set_parameter_field',
        ),
    ]
