# Generated by Django 6.1 on 2026-09-06 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('panels', '0004_backfill_panel_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='panel',
            name='allowed_roles',
            field=models.ManyToManyField(blank=True, related_name='panels', to='accounts.role'),
        ),
    ]
