# Generated by Django 6.1 on 2026-09-12 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panels', '0005_panel_allowed_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='panel',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='panel',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='panel',
            name='subcategory',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
