# Generated by Django 6.1 on 2026-08-08 21:53

import connections.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataConnection',
            fields=[
                ('id', models.SlugField(max_length=30, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('type', models.CharField(choices=[('sql', 'SQL database'), ('rest', 'REST endpoint'), ('s3', 'S3 bucket')], default='sql', max_length=15)),
                ('dialect', models.CharField(blank=True, max_length=60)),
                ('host', models.CharField(blank=True, max_length=255)),
                ('port', models.IntegerField(blank=True, null=True)),
                ('database', models.CharField(blank=True, max_length=255)),
                ('options', models.JSONField(blank=True, default=dict)),
                ('url', models.CharField(blank=True, max_length=500)),
                ('username', models.CharField(blank=True, max_length=120)),
                ('password', connections.fields.EncryptedTextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
