# Generated by Django 6.1 on 2026-08-16 19:14

import connections.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataconnection',
            name='config',
            field=connections.fields.EncryptedJSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='dataconnection',
            name='max_rows',
            field=models.IntegerField(blank=True, help_text='Blank = unlimited', null=True),
        ),
        migrations.AddField(
            model_name='dataconnection',
            name='timeout_seconds',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='dataconnection',
            name='type',
            field=models.CharField(choices=[('sql', 'SQL database'), ('rest', 'REST endpoint'), ('s3', 'S3 bucket'), ('file', 'File system')], default='sql', max_length=15),
        ),
    ]
