# Generated by Django 6.1 on 2026-09-06 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('connections', '0003_sample_connections'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataconnection',
            name='allowed_roles',
            field=models.ManyToManyField(blank=True, related_name='connections', to='accounts.role'),
        ),
    ]
