# Generated by Django 6.1 on 2026-09-13 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0004_dataconnection_allowed_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataconnection',
            name='type',
            field=models.CharField(choices=[('sql', 'SQL database'), ('s3', 'S3 bucket')], default='sql', max_length=15),
        ),
    ]
