# Generated by Django 6.1 on 2026-09-13 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0005_alter_dataconnection_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataconnection',
            name='type',
            field=models.CharField(choices=[('sql', 'SQL database'), ('s3', 'S3 bucket'), ('http', 'HTTP')], default='sql', max_length=15),
        ),
    ]
