# Generated by Django 6.1 on 2026-09-29 00:58

import connections.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0007_sample_http_connections'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataconnection',
            name='oauth_token',
            field=connections.fields.EncryptedTextField(blank=True),
        ),
        migrations.AddField(
            model_name='dataconnection',
            name='oauth_token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
