# Generated by Django 6.1 on 2026-10-09 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0008_oauth_token_cache'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataconnection',
            name='type',
            field=models.CharField(choices=[('sql', 'SQL database'), ('snowflake', 'Snowflake'), ('s3', 'S3 bucket'), ('http', 'HTTP')], default='sql', max_length=15),
        ),
    ]
